dist: xenial
language: python
python:
    - 3.4
    - 3.5
    - 3.6
    - 3.7
install:
    - pip install -r requirements-dev.txt
    - pip install coveralls
script:
    - python -m flake8
    - py.test tests -v --cov=vrc_t70
    - python setup.py check
    - python setup.py test
after_success:
    - coveralls --verbose
deploy:
  provider: pypi
  user: kittyhawk
  distributions: sdist bdist_wheel
  password:
    secure: jmM1dUYt8aRc9yWB4XFcLBFR+0562+lGL0yspRuWLNa8K0qd56Lpf0DRXW5vidSgfAex+9SDs2dNbQlGEjuTxWariLXKpwsm0JnitWHhRXpDSiUYYqDPFW2h2B/g4lB4XERR9AaEN+/XSkP9IFoyHAsW1KUaUsXKbFelmgIKiC7F6pngE8E6KkuGItGaMkjIsi/nE3na3aKTGWCrF0rM8h1DgR71e9WPfNZqJhvoimNfPUbr9pP5HKUyXzwElRyPYiMIvWVMZsU6gULqaQPjJLhPNDh9XbxhcCOp5Wq6IDZh8xf2/hjO+yehm5iUNxW8+D7pVW0Nrw6lSPSWD1LNlvYAe3UoIBzYG7RDrDepqqDRkRLqrtYL5ibV+Yx0PNNjaxqdbioxb+GZCt7mnt9K19m7yK0pxOroeEPgxFl3fC3/X7qs3YhX1+7twqks4o6G9WwD+JAZlfXv7t6caabQv1THTXJFmDQTotnQBv1oUV/+nh2tmk3xF18FtdU/B/EpNED+ZNW4TQxw6wtK4g0EOPV3tgMzqX30GfMnx+nj1YAV022ZGa8byT/ZSmS1syxEXzO9ZrQU3NAvNFaGtJzOoAv/Vmz00xW+Aa+tGPLdNUMA+EDzT6UISfnphttnGHBx8+t/BiuuK92w+noocNmTWXdHW/1Nf3/RiOWPrFaL/VE=
  on:
    tags: false
    branch: master
    condition: $TRAVIS_PYTHON_VERSION = "3.6"
