language: python
python:
    - 3.3
    - 3.4
    - 3.5
    - 3.6	
install:
    - pip install -r requirements-dev.txt
    - pip install coveralls
    - pip install python-coveralls

script:
    - py.test tests -v --cov=vrc_t70
after_success:
    - coveralls
