class VrcT70Commands:
    PING = 0x01
    GET_TEMPERATURE_OF_DEVICE = 0x02
    GET_TEMPERATURES_ON_TRUNK = 0x03
    GET_DEVICE_UNIQUE_NUMBER = 0x04
    GET_DEVICES_UNIQUE_ON_TRUNK = 0x05
    SET_SESSION_ID = 0x06
    GET_SESSION_ID = 0x07
    SET_NEW_DEVICE_ADDRESS = 0x08

    RESCAN_DEVICES_ON_TRUNK = 0x09

    GET_SENSORS_COUNT_ON_TRUNK = 0x0A
